### ISSUE TITLE
Job Icons on Nameplates

### ISSUE THREAD

**Issue by Pilzinsel64** [Pilzinsel64/PlayerTags#1]
To get job icons or a larger icon size there are some steps to do before because of limitations.
PR: (comming soon)
Refered Issues: https://github.com/r00telement/PlayerTags/issues/8, https://github.com/r00telement/PlayerTags/issues/12

## Current behavior and limits:
- Right now the role icons are placed as string in the text element using `IconPayload` by a given `BitmaFontIcon` that does only have role icons.
- The size of the icons is limited to the current font size of the whole text nameplate element.

## What could be done?
- Step 1:
  - Create a basic public library that includes some code from Player Tags and Party Icons. With this library it is possible to use the logic of the status/job icon from Party Icons within Player Tags.
- Step 2: Extend the library to include the ability to fully customize the whole nameplate (e.g. by adding own nodes such a Image Node).

## Todo:
- [x] Implement version 1 of the library
- [x] Integrate the library in Player Tags
- [x] Implement the job icon feature using the library
- [x] Extend Config Ui for job icon
- [x] (Add Config Ui to customize status icon prior list)

## Follow-up
- Extend library to be able to create additional Image Nodes and show the job icon on several positions.
- Show role icon on a Image Node ("RoleIcons" in IconSets). This will fix the small size.

## References
- [Messages in Party Icons Forum on goat Discord Server](https://discord.com/channels/581875019861328007/1036178399711998042/1036955295726960640)
  - Full detailed description of the whole problematic and ways to fix
- Fixes https://github.com/r00telement/PlayerTags/issues/12
- https://github.com/r00telement/PlayerTags/issues/8

**Comment by Pilzinsel64** [comment]
Since implementing this features would include a lot of stuff and code from PartyIcons, I will stop working on this here.
Feel free to open a Pull Request, if you have too much time. :D

Instead I made a description how to basic combine this plugin with PartyIcons.
https://github.com/Pilzinsel64/PlayerTags/blob/main/PlayerTags/Documentation/How%20To%20-%20Combine%20with%20PartyIcons.md

**Comment by Jacien** [comment]
It'd be cool if the glowing gold Job/class icons could be implemented. I mainly used those from PartyIcons, but the issue with that plugin is that it'll block regular icons like the AFK/Busy/Cutscene. So I opted to use this plugin instead, cause it's simple/clean and doesn't block the regular icons. Took some getting used to text, but it's nice.

But if the icons are ever looked into again, the ingame Icon IDs for the glowing class/job icons are:
`062301 - Gladiator
062302 - Pugilist
062303 - Marauder
062304 - Lancer
062305 - Archer
062306 - Conjurer
062307 - Thaumaturge
062308 - Arcanist
062309 - Rogue
062310 - Carpenter
062311 - Blacksmith
062312 - Armorer
062313 - Goldsmith
062314 - Leatherworker
062315 - Weaver
062316 - Alchemist
062317 - Culinarian
062318 - Miner
062319 - Botanist
062320 - Fisher
062401 - Paladin
062402 - Monk
062403 - Warrior
062404 - Dragoon
062405 - Bard
062406 - White Mage
062407 - Black Mage
062408 - Summoner
062409 - Scholar
062410 - Ninja
062411 - Machinist
062412 - Dark Knight
062413 - Astrologian
062414 - Samurai
062415 - Red Mage
062416 - Blue Mage
062417 - Gunbreaker
062418 - Dancer
062419 - Reaper
062420 - Sage`

**Comment by Pilzinsel64** [comment]
Thanks @Jacien
I did see them in PartyIcons too. Will use them when needed. ;)
The problem is that I can't put normal icons into a text. I can only use icons that are within [this enum](https://goatcorp.github.io/Dalamud/api/Dalamud.Game.Text.SeStringHandling.BitmapFontIcon.html). That's why there are only job icons atm and why PartyIcons displays the icon on the place of the status icon (because it's the place for real icons in the nameplate).

**Comment by Pilzinsel64** [comment]
There seems things possible that I thought that are not.
https://discord.com/channels/581875019861328007/653504487352303619/1017686190113169419

**Comment by Pilzinsel64** [comment]
Updated the whole issue at the top with up-to-date description and plans.

**Comment by Pilzinsel64** [comment]
![grafik](https://user-images.githubusercontent.com/23138465/200553032-7a49355d-3df4-4475-bb52-bf44149c5e49.png)
